sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
- docker ps 
# build image
- docker build -t icemanaf/rpi-arm-test:build .
# test image
- sudo docker run --privileged --rm icemanaf/rpi-arm-test:build uname -a
# push to docker
- echo $TRAVIS_TAG
- echo $TRAVIS_BRANCH
#Login to Docker Hub
- docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD