sudo: required
services:
- docker
language: bash
env:
- TAG="icemanaf/rpi-arm-test"
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
- docker ps 
# build image
- docker build -t $TAG .
# test image
- sudo docker run --privileged --rm $TAG uname -a
# push to docker
- echo $TRAVIS_TAG
- echo $TRAVIS_BRANCH
- echo $TRAVIS_BUILD_NUMBER
#Login to Docker Hub
- >
  if [$TRAVIS_BRANCH=="master"];
    docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    docker tag $TAG $TAG:$TRAVIS_BUILD_NUMBER
    docker push $TAG:$TRAVIS_BUILD_NUMBER
  fi